In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
# Example Dataset

numeric_data = pd.DataFrame({
    'Salary': [30000,45000,60000,80000,120000],
    'Age': [25,32,47,51,62]
})
numeric_data

   Salary  Age
0   30000   25
1   45000   32
2   60000   47
3   80000   51
4  120000   62

In [3]:
#Standard Scaler
std_scaler = StandardScaler()
std_scaler = std_scaler.fit_transform(numeric_data)
df = pd.DataFrame(std_scaler, columns = numeric_data.columns)
print("\nStandard Scaled Data:\n ", df)

Standard Scaled Data:
       Salary       Age
0 -1.184341 -1.382872
1 -0.704203 -0.856780
2 -0.224065  0.270562
3  0.416120  0.571186
4  1.696489  1.397904

In [4]:
minmax_scaler = MinMaxScaler()
minmax_scaler = minmax_scaler.fit_transform(numeric_data)
df1 = pd.DataFrame(minmax_scaler, columns = numeric_data.columns)
print("Min-Max Scaled Data:\n", df1)

Min-Max Scaled Data:
      Salary       Age
0  0.000000  0.000000
1  0.166667  0.189189
2  0.333333  0.594595
3  0.555556  0.702703
4  1.000000  1.000000

## Encoding Categorical variables

In [5]:
# converts text label to numeric format for Ml Models
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [6]:
#Sample Data

cat_data = pd.DataFrame({
    "Department":["HR", "Sales", "IT", "HR", "IT"]
})

cat_data

  Department
0         HR
1      Sales
2         IT
3         HR
4         IT

In [7]:
#LabelEncoding
label_encoder = LabelEncoder()
cat_data['Dept_Label'] = label_encoder.fit_transform(cat_data["Department"])
print("\nLabel Encoder:\n", cat_data)

Label Encoder:
   Department  Dept_Label
0         HR           0
1      Sales           2
2         IT           1
3         HR           0
4         IT           1

In [8]:
one_hot = OneHotEncoder()
cat_data['Dept_One_Hot_Label'] = label_encoder.fit_transform(cat_data["Department"])
print("\nLabel OneHot Encoder:\n", cat_data)

Label OneHot Encoder:
   Department  Dept_Label  Dept_One_Hot_Label
0         HR           0                   0
1      Sales           2                   2
2         IT           1                   1
3         HR           0                   0
4         IT           1                   1

In [11]:
cat_data_ohe = pd.get_dummies(cat_data['Department'], prefix = 'Dept').astype(int)
print("\One-Hot Encoded:\n\n", cat_data_ohe)

\One-Hot Encoded:

    Dept_HR  Dept_IT  Dept_Sales
0        1        0           0
1        0        0           1
2        0        1           0
3        1        0           0
4        0        1           0

## Normalization

In [13]:
from sklearn.preprocessing import Normalizer

# Example data

X = np.array([[3.0,4.0],[1.0,0.0],[0.0,8.0]])
print("Original Data:\n",X)
normalizer = Normalizer()
normalized_data = normalizer.fit_transform(X)
print("Normalized Data:\n", normalized_data)

Original Data:
 [[3. 4.]
 [1. 0.]
 [0. 8.]]
Normalized Data:
 [[0.6 0.8]
 [1.  0. ]
 [0.  1. ]]

## Case Study: Retail Customer Data

### Scenario : You have a retail customer dataset with income, age and gender You want to prepare it for ML model input

In [14]:
raw_data = pd.DataFrame({
    'CustomerID': [101,102,103,104,105],
    'Gender': ['Male','Female','Female','Male','Female'],
    'Age': [23,45,31,35,52],
    'Income': [25000,52000,38000,45000,61000]
})
raw_data

   CustomerID  Gender  Age  Income
0         101    Male   23   25000
1         102  Female   45   52000
2         103  Female   31   38000
3         104    Male   35   45000
4         105  Female   52   61000

In [15]:
data = raw_data.drop(columns = "CustomerID")
data

   Gender  Age  Income
0    Male   23   25000
1  Female   45   52000
2  Female   31   38000
3    Male   35   45000
4  Female   52   61000

In [17]:
label_coder = LabelEncoder()
data['Gender'] = label_coder.fit_transform(data['Gender'])
data

   Gender  Age  Income
0       1   23   25000
1       0   45   52000
2       0   31   38000
3       1   35   45000
4       0   52   61000

In [22]:
from sklearn.preprocessing import  MinMaxScaler
minmaxscaler= MinMaxScaler()
scaled = minmaxscaler.fit_transform(data[['Age','Income']])
data[['Age','Income']] = scaled
print("\nNormalized data\n", data)

Normalized data
    Gender       Age    Income
0       1  0.000000  0.000000
1       0  0.758621  0.750000
2       0  0.275862  0.361111
3       1  0.413793  0.555556
4       0  1.000000  1.000000