# Data Wrangling & File Handling in Various Format in Python
## (Reading/Writing Text, TSV, JSON, Files in Python)

### Data Wrangling & File Handling in Various Formats

In Real-World data analysis, information comes in different file format like text(`.txt`), TSV(`.tsv`), and JSON(`.json`).

Python provide built-in and library-based tools to read, write and process these format efficiently.

This topic help us how to load data from different sources and prepare it for analysis and modeling.

## Introduction to File Formats

### Text Files(`.txt`) :

- Plain text without structured formatting.
- Used for simple data storage(e.g., logs, notes).
- Handled via Python's built-in `open()` function.

### Writing to a text file using built-in open() function

In [1]:
with open('example_text.txt', 'w') as file:
    file.write("This is sample file for text.\n")
print("File created successfully")

File created successfully

### Key concepts:

- **open():** Opens a file in write('w') or read('r') or other file mode.
- **write():** Writes data to the file.
- **with statement:** Ensure proper file clousure after operations.

In [2]:
# Can you try to print multiple lines using write in text file.
with open('example_text.txt', 'a') as file:
    file.write("This is second sample file for text.\n")
    file.write("This is third sample file for text.\n")
    
print("File updated successfully")

File updated successfully

In [5]:
with open('example_text.txt', 'a') as file:
    for i in range(6):
        file.write(f"This is {i} sample file for text.\n")
print("File updated successfully")

File updated successfully

### Reading a text file using built-in open() function.

In [6]:
with open('example_text.txt', 'r') as file:
    data = file.read()
    print(data)

This is sample file for text.
This is second sample file for text.
This is third sample file for text.
This is 0 sample file for text.
This is 1 sample file for text.
This is 2 sample file for text.
This is 3 sample file for text.
This is 4 sample file for text.
This is 5 sample file for text.
This is 0 sample file for text.
This is 1 sample file for text.
This is 2 sample file for text.
This is 3 sample file for text.
This is 4 sample file for text.
This is 5 sample file for text.

### Key concepts:

- **read():** Reads the entire file content.
- **readlines():** Returns a list of lines(useful for multi-line files).

In [7]:
with open('example_text.txt', 'r') as file:
    data = file.readlines()
    print(data)

['This is sample file for text.\n', 'This is second sample file for text.\n', 'This is third sample file for text.\n', 'This is 0 sample file for text.\n', 'This is 1 sample file for text.\n', 'This is 2 sample file for text.\n', 'This is 3 sample file for text.\n', 'This is 4 sample file for text.\n', 'This is 5 sample file for text.\n', 'This is 0 sample file for text.\n', 'This is 1 sample file for text.\n', 'This is 2 sample file for text.\n', 'This is 3 sample file for text.\n', 'This is 4 sample file for text.\n', 'This is 5 sample file for text.\n']

In [8]:
lines = [ 
    "This is 0 sample file for text.",
    "This is 1 sample file for text.",
    "This is 2 sample file for text.",
    "This is 3 sample file for text.",
    "This is 4 sample file for text.",
    "This is 5 sample file for text."
    ]

with open('example_multi.txt', 'w') as file:
    for l in lines:
        file.write(l + "\n")
print("Multi-line file is created")

Multi-line file is created

### Key Concept:

**`\n`:** Newline character to seperate lines.

### A python code to read txt file from specific location

In [9]:
with open('example_multi.txt', 'r') as file:
    lines = file.readlines()

for l in lines:
    print(l.strip())

This is 0 sample file for text.
This is 1 sample file for text.
This is 2 sample file for text.
This is 3 sample file for text.
This is 4 sample file for text.
This is 5 sample file for text.

### Key Concepts:

- Absolute/relative paths for file access.

- **`strip()`:** Removes leading/trailing whitespace( including \n)

## TSV(`Tab-Seperated Values`):

- stores tabular data with tabs(\\t) as deliniters.
- Similar to CSV but uses tabs instead of commas.
- Ideal for datasets with fields containing commas.

### Compatibility with Tools:

- TSV works seamlessly with spreadsheet software( Excel, Google Sheets), databases and data analysis tools( Pandas, R).

### Avoiding Parsing Issues:

- TXT files with spaces/commas can cause ambiguity (e.g., "New York" vs two columns).
- TSV's tabs are unambiguous delimiters.

### Efficiency:

- TSV is more compacts than CSV for certain data(e.g., when text conatains commas).

### Writing the DataFrame to a TSV File

In [10]:
import pandas as pd

data = {
    'Emp_ID': [101,102,103,104],
    'Name': ['Rahul Sharma', 'Priya Patel', 'Amit Singh', 'Neeta Rao'],
    'Department': ['HR', 'Finance', 'IT','Marketing'],
    'Salary': [50000,65000,80000,55000],
    'Joining_Date': ['2020-01-15','2019-05-22','2021-11-10','2022-03-05'],
    'City': ['Mumbai', 'Delhi', 'Bangalore', 'Hydredabad']
}

data

{'Emp_ID': [101, 102, 103, 104],
 'Name': ['Rahul Sharma', 'Priya Patel', 'Amit Singh', 'Neeta Rao'],
 'Department': ['HR', 'Finance', 'IT', 'Marketing'],
 'Salary': [50000, 65000, 80000, 55000],
 'Joining_Date': ['2020-01-15', '2019-05-22', '2021-11-10', '2022-03-05'],
 'City': ['Mumbai', 'Delhi', 'Bangalore', 'Hydredabad']}

In [11]:
df = pd.DataFrame(data)
df

   Emp_ID          Name Department  Salary Joining_Date        City
0     101  Rahul Sharma         HR   50000   2020-01-15      Mumbai
1     102   Priya Patel    Finance   65000   2019-05-22       Delhi
2     103    Amit Singh         IT   80000   2021-11-10   Bangalore
3     104     Neeta Rao  Marketing   55000   2022-03-05  Hydredabad

In [12]:
df.to_csv('tab_example.tsv', sep= '\t', index = False)

### Key Concepts:

- **`sep = '\t'`**: Specify tab as the delimiter.
- **`index = False`** Avoids writing row indicies(by default).
- **`index = True`** If your DataFrame has a custom index (e.g., dates, employee ID's) that you want to preserve.

## Reading the TSV File

In [15]:
df_read = pd.read_csv('tab_example.tsv', sep='\t')

## Displaying the content
print(df_read.head())

   Emp_ID          Name Department  Salary Joining_Date        City
0     101  Rahul Sharma         HR   50000   2020-01-15      Mumbai
1     102   Priya Patel    Finance   65000   2019-05-22       Delhi
2     103    Amit Singh         IT   80000   2021-11-10   Bangalore
3     104     Neeta Rao  Marketing   55000   2022-03-05  Hydredabad

In [16]:
df_read

   Emp_ID          Name Department  Salary Joining_Date        City
0     101  Rahul Sharma         HR   50000   2020-01-15      Mumbai
1     102   Priya Patel    Finance   65000   2019-05-22       Delhi
2     103    Amit Singh         IT   80000   2021-11-10   Bangalore
3     104     Neeta Rao  Marketing   55000   2022-03-05  Hydredabad

### key Concepts:

- **`pd.read_csv()`:** Can read TSV files with `sep = '\t'`.

# Same Data, Different Formats

| Data Example        | CSV Format (Commas)                    | TSV Format (Tabs)               |
|--------------------|----------------------------------------|--------------------------------|
| Simple Data        | `Apple,1.99,Red `                        | `Apple    1.99    Red`           |
| Data with Commas   | `"Apple, Green",1.99,Green`              | `Apple, Green    1.99    Green`  |
| Data with Quotes   | `"Apple \"Honey\"",2.50,Yellow`          | `Apple "Honey"    2.50    Yellow`|
| Readability        | `Harder (quotes/escapes)`                | `Cleaner (no conflicts)`         |

### When to Use Which?

- **Use CSV when:**
    - Working with Excel/Google Sheets(default format).
    - Data is simple(no commas in text).
- **Use TSV when:**
  - Data contains commas, quotes or multi-line text.
  - Processing logs, NLP data or large datasets.

## JSON (JavaScript Object Notation):

- Lightweight data interchange format.
- Uses key-value pairs and nested structures.
- Commonly used for API's and configuration files.

In [17]:
import json

data = {
    "employees": [
        {"name": "John", "age": 30, "department" : "Sales"},
        {"name": "Meera", "age": 25, "department" : "Marketing"},
        {"name": "Rahul", "age": 35, "department" : "HR"}
    ]
}

# Writing the dictionary to a JSON file
with open('json_example.json', 'w') as file:
          json.dump(data, file, indent= 4)

### Key Concepts: 

- `json.dump(data, file, indent= 4)`: This function writes dictionary `data` into the file in JSON format.
  - `data`: This is the dictionary you eant to write to the JSON file.
  - `file`: This refers to the file object created in the `with` statement. It's where the JSON data will be written.
  - `indent= 4`: This argument makes the JSON file more readable by adding an indentation of 4 spaces to each level in the data hierarchy. This makes it easier to read when you open the file.
- **json.dumps():** Serializes Python objects to JSON.
- **indent:** Improves readability by formatting with sapces.

## Reading the JSON file

In [18]:
import json

# Reading the JSON file
with open('json_example.json', 'r') as file:
    data = json.load(file)

#Printing the data in a more readable format
print("Employee Information:")
for emp in data['employees']:
    print(f"Name: {emp['name']}, Age: {emp['age']}, Department: {emp['department']}")

Employee Information:
Name: John, Age: 30, Department: Sales
Name: Meera, Age: 25, Department: Marketing
Name: Rahul, Age: 35, Department: HR

### Key Concepts:

- **`json.load()`**: Parses JSON into a Python dictionary.

## Summary:

# File Formats at a Glance

| Format | Structure      | Best For           | Python Tools                          |
|--------|---------------|-------------------|--------------------------------------|
| TXT    | Raw text      | Logs, notes       | `open()`                             |
| CSV    | Comma tables  | Excel data        | `csv` module / `pandas`              |
| TSV    | Tab tables    | Text with commas  | `csv` (with `delimiter='\t'`)        |
| JSON   | Nested data   | APIs, configs     | `json` module                        |