# Assignment 2 - Working with Pandas

## Objective: Learn to create and manipulate dataframes for data analysis.

### Step 1: Install Pandas using:

In [1]:
# !pip install pandas

### Step 2: Create a new Python script pandas_assignment.ipynb. Import Pandas and follow these steps:

### 1. Create a DataFrame with the following data:  
  


  data = {
      'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
      'Age': [24, 27, 22, 32, 29],
      'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
      'Salary': [45000, 54000, 50000, 62000, 47000]
  }

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(  data = {
      'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
      'Age': [24, 27, 22, 32, 29],
      'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
      'Salary': [45000, 54000, 50000, 62000, 47000]
  })

In [6]:
df.head()

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

####  a. Print the first five rows of the DataFrame.

In [8]:
df.head(5)

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

#### b. Get the summary statistics of the 'Age' and 'Salary' columns.

In [12]:
df[['Age', 'Salary']].describe()

             Age        Salary
count   5.000000      5.000000
mean   26.800000  51600.000000
std     3.962323   6730.527468
min    22.000000  45000.000000
25%    24.000000  47000.000000
50%    27.000000  50000.000000
75%    29.000000  54000.000000
max    32.000000  62000.000000

#### c. Calculate the average salary of employees in the 'HR' department.

In [14]:
hr_avg_salary = df[df['Department'] == 'HR']['Salary'].mean()
print(f" average salary of employees in the 'HR' department: {hr_avg_salary}")

 average salary of employees in the 'HR' department: 46000.0

### 2. Add a new column, 'Bonus', which is 10% of the salary.

In [15]:
df['Bonus'] = df['Salary'] * 0.10
df

      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
1      Bob   27    Finance   54000  5400.0
2  Charlie   22         IT   50000  5000.0
3    Diana   32  Marketing   62000  6200.0
4      Eve   29         HR   47000  4700.0

### 3. Filter the DataFrame to show employees aged between 25 and 30.

In [17]:
filtered_df = df[(df['Age'] >= 25) & (df['Age'] <= 30)]
filtered_df

  Name  Age Department  Salary   Bonus
1  Bob   27    Finance   54000  5400.0
4  Eve   29         HR   47000  4700.0

### 4. Group the data by 'Department' and calculate the average salary for each department.

In [18]:
df.groupby('Department')['Salary'].mean()

Department
Finance      54000.0
HR           46000.0
IT           50000.0
Marketing    62000.0
Name: Salary, dtype: float64

### 5. Sort the DataFrame by 'Salary' in ascending order and save the result to a new CSV file.

In [19]:
sorted_df = df.sort_values(by='Salary', ascending = True)
sorted_df

      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
4      Eve   29         HR   47000  4700.0
2  Charlie   22         IT   50000  5000.0
1      Bob   27    Finance   54000  5400.0
3    Diana   32  Marketing   62000  6200.0

In [20]:
sorted_df.to_csv('sorted_employees.csv', index=False)