# Pandas:  Series & DataFrame data structures

This notebook covers:
- **Pandas Data Structures**: Series & DataFrame
- **Handling DataFrames**: Loading, Inspecting, and Modifying Data
- **Handling Missing Data**: Strategies to deal with NaN values
- **Grouping and Aggregation**: Summarizing data
- **Data Visualization**: Analyzing trends visually

##  **Introduction** : Pandas

*Pandas is  an open-source  powerful Python library for data manipulation and analysis.* 

*It offers powerful, flexible data structures such as Series (1D) and DataFrame (2D).*

## Why Use Pandas?
- Easy handling of missing data
- Powerful group-by functionality
- Fast and efficient merging, reshaping, slicing, and dicing of data
- Read/write support for many file formats: CSV, Excel, JSON, SQL, etc.

##  **Understanding Pandas Series , DataFrame Data Structures**

### **Definition & Functionality**
- **Series**: A one-dimensional labeled array, similar to a column in a spreadsheet.

- **DataFrame**: A two-dimensional table-like structure with labeled rows and columns, similar to an Excel sheet.

In [72]:
import pandas as pd
import numpy as np

### Creating Series manually

In [73]:
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print("Series:\n", s)

Series:
 a    10
b    20
c    30
d    40
dtype: int64

In [74]:
prices = [649000, 391000, 5476000, 1786000, 1091000]
carnames = ['swift', 'santro', 'audi', 'elantra', 'bolero']

In [75]:
car_series = pd.Series(data = prices, index = carnames)
car_series

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
dtype: int64

In [76]:
type(car_series)

pandas.core.series.Series

In [77]:
car_series = pd.Series(prices)
car_series

0     649000
1     391000
2    5476000
3    1786000
4    1091000
dtype: int64

In [78]:
car_series = pd.Series(prices, carnames, name = 'price')
car_series

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [79]:
# The `name` attribute for the Pandas series is optional but helpful and
# makes the data organization neater and easier to handle.

### Example
Creating series from dictionaries

In [80]:
entries = {'swift': 649000,
           'santro': '391000',
           'audi': 5476000,
           'elantra': 1786000,
           'bolero': 1091000}
car_series = pd.Series(data = entries, name = 'price')
car_series

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: object

In [81]:
type(car_series['swift'])

int

In [82]:
type(car_series['santro']) # as santro price is string data type

str

In [83]:
len(car_series)

5

In [84]:
car_series.shape

(5,)

### Accessing data from series

In this section, we will study various methods to access data from series.

### Example
Accessing data from series using logical conditions

In [85]:
entries = {'swift': 649000,
           'santro': 391000,
           'audi': 5476000,
           'elantra': 1786000,
           'bolero': 1091000}
car_series = pd.Series(data = entries, name = 'price')
car_series

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [86]:
### display all model of car having price more than 10,00,000 rupees (10 Lacs )

In [87]:
car_series > 1000000

swift      False
santro     False
audi        True
elantra     True
bolero      True
Name: price, dtype: bool

In [88]:
car_series[car_series>1000000]

audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [89]:
car_series[car_series > 1000000].index[0]

'audi'

In [90]:
car_series[car_series > 1000000].index[2]

'bolero'

In [91]:
car_series[car_series > 1000000].values[0]

np.int64(5476000)

In [92]:
car_series[car_series > 1000000].values[2]

np.int64(1091000)

In [93]:
car_series[(car_series > 1000000) & (car_series < 2000000)]

elantra    1786000
bolero     1091000
Name: price, dtype: int64

### Quiz
Consider the series shown below:
```
cust_names = ['Hemang', 'Farheen', 'Himadri', 'Monisha']
cust_bill = [256.78, 434.53, 109.25, 529.42]
cust_info = pd.Series(cust_bill, cust_names)
```
Write code to print the names of the customers who have spent more than 300 rupees.

In [94]:
cust_names = ['Hemang', 'Farheen', 'Himadri', 'Monisha']
cust_bill = [256.78, 434.53, 109.25, 529.42]
cust_info = pd.Series(cust_bill, cust_names)

In [95]:
list(cust_info[cust_info>300].index)

['Farheen', 'Monisha']

### Example
Accessing data from series using the `.loc[]` method

In [96]:
entries = {'swift': 649000,
           'santro': 391000,
           'audi': 5476000,
           'elantra': 1786000,
           'bolero': 1091000}
car_series = pd.Series(data = entries, name = 'price')
car_series

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [97]:
car_series.loc['swift']

np.int64(649000)

In [98]:
car_series.loc[['swift']]

swift    649000
Name: price, dtype: int64

In [99]:
car_series.loc[['swift', 'audi']]

swift     649000
audi     5476000
Name: price, dtype: int64

In [100]:
car_series.loc['swift':'elantra']

swift       649000
santro      391000
audi       5476000
elantra    1786000
Name: price, dtype: int64

### Note that this is similar to NumPy array slicing, but the `.loc[]` method is inclusive of the stop value as well.

In [101]:
car_series.loc['santro':'audi']

santro     391000
audi      5476000
Name: price, dtype: int64

In [102]:
car_series.loc[:'elantra']

swift       649000
santro      391000
audi       5476000
elantra    1786000
Name: price, dtype: int64

### Example
Accessing data from series using the `.iloc[]` method

In [103]:
entries = {'swift': 649000,
           'santro': 391000,
           'audi': 5476000,
           'elantra': 1786000,
           'bolero': 1091000}
car_series = pd.Series(data = entries, name = 'price')
car_series

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [104]:
car_series.iloc[0]

np.int64(649000)

In [105]:
car_series.iloc[3]

np.int64(1786000)

In [106]:
car_series.iloc[[3]]

elantra    1786000
Name: price, dtype: int64

In [107]:
car_series.iloc[[0, 2, 4]]

swift      649000
audi      5476000
bolero    1091000
Name: price, dtype: int64

In [108]:
car_series.iloc[0:2]

swift     649000
santro    391000
Name: price, dtype: int64

Note that the `.iloc[]` method is not inclusive of the stop element like the `.loc[]` method. The `.iloc[]` method is very similar to NumPy array indexing and slicing.

In [109]:
car_series.iloc[-1]

np.int64(1091000)

In [110]:
car_series.iloc[[-1]]

bolero    1091000
Name: price, dtype: int64

In [111]:
car_series.iloc[1:5:2]

santro      391000
elantra    1786000
Name: price, dtype: int64

In [112]:
car_series.iloc[::-1]

bolero     1091000
elantra    1786000
audi       5476000
santro      391000
swift       649000
Name: price, dtype: int64

### Quiz
Consider the series shown below:
```
cust_names = ['Mahesh', 'Farheen', 'Himadri', 'Monisha']
cust_bill = [256.78, 434.53, 109.25, 529.42]
cust_info = pd.Series(cust_bill, cust_names)
```
Use the different methods you have studied to extract the bill amounts for Mahesh and Monisha.

In [113]:
cust_names = ['Mahesh', 'Farheen', 'Himadri', 'Monisha']
cust_bill = [256.78, 434.53, 109.25, 529.42]
cust_info = pd.Series(cust_bill, cust_names)

In [114]:
cust_info[['Mahesh', 'Monisha']]

Mahesh     256.78
Monisha    529.42
dtype: float64

In [115]:
cust_info.iloc[[0,3]]

Mahesh     256.78
Monisha    529.42
dtype: float64

## **Handling DataFrames**

### **Definition & Functionality**
- **Loading Data**: Import CSV, Excel, or SQL files into Pandas DataFrames.
- **Inspecting Data**: View structure, columns, and basic statistics.
- **Modifying Data**: Add, rename, or remove columns.

### Creating DataFrame manually

In [116]:

df = pd.DataFrame({
    'Product': ['A', 'B', 'C'],
    'Price': [100, 150, 200],
    'Quantity': [5, 3, 4]
})
print("\nDataFrame:\n", df)

DataFrame:
   Product  Price  Quantity
0       A    100         5
1       B    150         3
2       C    200         4

### How to create csv file from exisiting dataframe data

In [117]:
import pandas as pd

In [118]:
df_csv = pd.DataFrame({
    'Product': ['Soap', 'Shampoo', 'Toothpaste', 'Oil'],
    'Price': [30, 120, 45, 150],
    'Units_Sold': [100, 60, 80, 50]
})
df_csv

      Product  Price  Units_Sold
0        Soap     30         100
1     Shampoo    120          60
2  Toothpaste     45          80
3         Oil    150          50

In [119]:
# Save to CSV for use (in real scenario you would read from file)
df_csv.to_csv("retail_sales.csv", index=False)

print('file created successfully')

file created successfully

### Read CSV using pandas

In [120]:
sales_data = pd.read_csv("retail_sales.csv")

print("\n CSV Data from 'retail_sales.csv':\n\n", sales_data)

 CSV Data from 'retail_sales.csv':

       Product  Price  Units_Sold
0        Soap     30         100
1     Shampoo    120          60
2  Toothpaste     45          80
3         Oil    150          50

In [121]:
sales_data

      Product  Price  Units_Sold
0        Soap     30         100
1     Shampoo    120          60
2  Toothpaste     45          80
3         Oil    150          50

In [122]:
print("\nDisplay Price column:")

sales_data['Price']

Display Price column:

0     30
1    120
2     45
3    150
Name: Price, dtype: int64

### Quiz Time

### Quiz display Units_Sold column value

In [123]:
sales_data['Units_Sold']

0    100
1     60
2     80
3     50
Name: Units_Sold, dtype: int64

### display Product and Price columns value together

In [124]:
sales_data[['Product','Price']]

      Product  Price
0        Soap     30
1     Shampoo    120
2  Toothpaste     45
3         Oil    150

In [125]:
sales_data

      Product  Price  Units_Sold
0        Soap     30         100
1     Shampoo    120          60
2  Toothpaste     45          80
3         Oil    150          50

In [126]:
sales_data[['Price','Units_Sold']]

   Price  Units_Sold
0     30         100
1    120          60
2     45          80
3    150          50

### How to read csv file

In [127]:
import pandas as pd

# Load the dataset
file_path = "pharma_sales_data.csv" # NOTE USE \\ AS PATH SEPERATOR
df = pd.read_csv(file_path)

In [128]:
df.head()

   Product_ID Product_Name      Category  Sales_Units  Revenue Region
0         101   PainRelief     Analgesic        500.0  25000.0  North
1         102   CoughSyrup  Cough & Cold        300.0  12000.0  South
2         103  AntibioticX    Antibiotic          NaN  40000.0   East
3         104     VitaminD    Supplement        700.0      NaN   West
4         105  DiabetesMed      Diabetes        450.0  31500.0  North

In [129]:
### Option 2 to read csv file

In [130]:
import pandas as pd

# Load the dataset
#file_path = "C:/Users/askpr/Tutedude/pharma_sales_data.csv" # NOTE USE / AS PATH SEPERATOR
file_path = r"pharma_sales_data.csv"
df = pd.read_csv(file_path)
df.head()

   Product_ID Product_Name      Category  Sales_Units  Revenue Region
0         101   PainRelief     Analgesic        500.0  25000.0  North
1         102   CoughSyrup  Cough & Cold        300.0  12000.0  South
2         103  AntibioticX    Antibiotic          NaN  40000.0   East
3         104     VitaminD    Supplement        700.0      NaN   West
4         105  DiabetesMed      Diabetes        450.0  31500.0  North

In [131]:
#opiton 3 
# r prefix: Stands for "raw" and ensures backslashes are treated literally.

# Without r: C:\\Users\\askpr\\Tutedude\\pharma_sales_data.csv (requires escaping backslashes with \\).

# With r: r"C:\Users\askpr\Tutedude\pharma_sales_data.csv"(no escaping needed).

In [132]:
# option 4 Best option
# Keep csv file and keep python file and csv files in same folder
# Now no need to give path , as python file will read csv file from current location 
# where python file is stored, and csv file is in same location, so it will read.

In [133]:
file_path = "pharma_sales_data.csv"
df = pd.read_csv(file_path)
df.head()

   Product_ID Product_Name      Category  Sales_Units  Revenue Region
0         101   PainRelief     Analgesic        500.0  25000.0  North
1         102   CoughSyrup  Cough & Cold        300.0  12000.0  South
2         103  AntibioticX    Antibiotic          NaN  40000.0   East
3         104     VitaminD    Supplement        700.0      NaN   West
4         105  DiabetesMed      Diabetes        450.0  31500.0  North

### To display top 7 records

In [134]:
df.head(7)

   Product_ID Product_Name      Category  Sales_Units  Revenue Region
0         101   PainRelief     Analgesic        500.0  25000.0  North
1         102   CoughSyrup  Cough & Cold        300.0  12000.0  South
2         103  AntibioticX    Antibiotic          NaN  40000.0   East
3         104     VitaminD    Supplement        700.0      NaN   West
4         105  DiabetesMed      Diabetes        450.0  31500.0  North
5         106      Antacid     Digestive          NaN  18000.0  South
6         107  AllergyPill       Allergy        600.0      NaN   East

###  To display bottom (last) 5 records

In [135]:
df.tail()

   Product_ID Product_Name    Category  Sales_Units  Revenue Region
3         104     VitaminD  Supplement        700.0      NaN   West
4         105  DiabetesMed    Diabetes        450.0  31500.0  North
5         106      Antacid   Digestive          NaN  18000.0  South
6         107  AllergyPill     Allergy        600.0      NaN   East
7         108      FluShot     Vaccine        800.0  56000.0   West

### **Pharmaceutical Case Study: Understanding Drug Sales Data**
A pharmaceutical company collects sales data to analyze drug demand across regions. The dataset contains:
- `Drug_Name`: Name of the pharmaceutical product.
- `Sales_Qty`: Number of units sold.
- `Region`: Sales region (North, South, East, West).
- `Revenue`: Total revenue from sales.

###  Inspecting Pharmaceutical Sales Data
A pharmaceutical company wants to inspect its dataset before analysis.

### Display basic information

In [136]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    8 non-null      int64
 1   Product_Name  8 non-null      object
 2   Category      8 non-null      object
 3   Sales_Units   6 non-null      float64
 4   Revenue       6 non-null      float64
 5   Region        8 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 516.0+ bytes

### Display summary statistics

In [137]:

df.describe()

       Product_ID  Sales_Units       Revenue
count     8.00000     6.000000      6.000000
mean    104.50000   558.333333  30416.666667
std       2.44949   180.046290  15938.684596
min     101.00000   300.000000  12000.000000
25%     102.75000   462.500000  19750.000000
50%     104.50000   550.000000  28250.000000
75%     106.25000   675.000000  37875.000000
max     108.00000   800.000000  56000.000000

## **Conclusion**
- Pandas simplifies pharmaceutical data analysis.
- DataFrames efficiently store and manipulate structured data.
- How to read csv file, Display data from csv file.
- basic functions like info(),describe()