# Creating DataFrames

Let’s look at different ways to create a Pandas `DataFrame` — the core data structure you’ll be using 90% of the time in data science.

-----------

## From Python Lists

In [1]:
import pandas as pd

In [2]:
data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]

In [3]:
 df = pd.DataFrame(data, columns=["Name", "Age"])

In [4]:
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

-------

## From Dictionary of Lists

Most common and readable format:

In [5]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

In [6]:
df = pd.DataFrame(data)

In [7]:
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

Each **key becomes a column**, and each list is the **column data**.

---------------

## From NumPy Arrays

In [9]:
import numpy as np

In [10]:
arr = np.array([[1, 2], [3, 4]])

In [11]:
df = pd.DataFrame(arr, columns=["A", "B"])

Make sure to provide column names!

---------------

## From CSV Files

In [12]:
df = pd.read_csv("data.csv")

In [13]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## EDA (Exploratory Data Analysis)

**Exploratory Data Analysis (EDA)** is an essential first step in any data science project.

It involves taking a deep look at the dataset to understand its structure, spot patterns, identify anomalies, and uncover relationships between variables. This process includes generating summary statistics, checking for missing or duplicate data, and creating visualizations like histograms, box plots, and scatter plots. The goal of EDA is to get a clear picture of what the data is telling you before applying any analysis or machine learning models.

By exploring the data thoroughly, you can make better decisions about how to clean, transform, and model it effectively.

Once your DataFrame is ready, run these to understand your data:

In [19]:
df.head()         # First 5 rows

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5

In [20]:
df.tail()         # Last 5 rows

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [21]:
df.info()         # Column info: types, non-nulls

<class 'pandas.DataFrame'>
Index: 9 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Actor                 9 non-null      str
 1   Film                  9 non-null      str
 2   Year                  9 non-null      int64
 3   Genre                 9 non-null      str
 4   BoxOffice(INR Crore)  9 non-null      int64
 5   IMDb                  9 non-null      float64
dtypes: float64(1), int64(2), str(3)
memory usage: 802.0 bytes

In [22]:
df.describe()     # Stats for numeric columns

              Year  BoxOffice(INR Crore)      IMDb
count     9.000000              9.000000  9.000000
mean   2018.555556            587.333333  7.355556
std       1.943651            608.840291  0.814112
min    2016.000000            111.000000  6.100000
25%    2018.000000            201.000000  7.000000
50%    2018.000000            342.000000  7.200000
75%    2019.000000            585.000000  8.200000
max    2023.000000           2024.000000  8.400000

In [23]:
df.columns        # List of column names

Index(['Actor', 'Film', 'Year', 'Genre', 'BoxOffice(INR Crore)', 'IMDb'], dtype='str')

In [24]:
df.shape          # (rows, columns)

(9, 6)

In [25]:
df.to_csv("data_updated.csv", index=False)

## Summary

* You can create DataFrames from lists, dicts, arrays, files, web, and SQL
* Use .head(), .info(), .describe() to quickly explore any dataset