# Data Selection & Filtering

Selecting the right rows and columns is the first step in analyzing any dataset. Pandas gives you several powerful ways to do this.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## Selecting Rows & Columns

### Selecting Columns

In [6]:
df["Actor"]        # Single column (as Series)

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: str

In [7]:
df[["Actor", "IMDb"]]     # Multiple columns (as DataFrame)

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

## Selecting Rows by Index

Use `.loc[]` (label-based) and `.iloc[]` (position-based):

In [8]:
df.loc[0]                # First row (by label)

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [9]:
df.iloc[0]               # First row (by position)

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

## Select Specific Rows and Columns

In [10]:
df.loc[0, "Actor"]        # Value at row 0, column 'Name'

'Shah Rukh Khan'

In [11]:
df.iloc[0, 1]            # Value at row 0, column at index 1

'Pathaan'

You can also slice:

In [12]:
df.loc[0:2, ["Actor", "IMDb"]]   # Rows 0 to 2, selected columns

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0
2      Aamir Khan   8.4

In [13]:
df.iloc[0:2, 0:2]              # Rows and cols by index position

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

## Fast Access: `.at` and `.iat`

These are optimized for single element access:

In [14]:
df.at[0, "Actor"]       # Fast label-based access

'Shah Rukh Khan'

In [16]:
df.iat[0, 0]           # Fast position-based access

'Shah Rukh Khan'

## Filtering with Conditions

### Simple Condition

In [18]:
df[df["IMDb"] > 6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

### Multiple Conditions (AND / OR)

In [19]:
df[(df["IMDb"] > 6) & (df["Year"]==2018)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5

In [22]:
df[(df["Year"] == 2018) | (df["IMDb"] >6)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

`Use parentheses around each condition!`

----

## Querying with `.query()`

The `.query()` method in pandas lets you filter DataFrame rows using a string expression — it's a more readable and often more concise alternative to using boolean indexing.

This is a cleaner, SQL-like way to filter:

In [23]:
df.query("IMDb > 6 and Genre == 'Action'")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

Dynamic column names:

In [28]:
rating = "IMDb"

df.query(f"{rating} > 8")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

Here are the main **rules and tips** for using `.query()` in pandas:

### 1. Column names become variables

You can reference column names directly in the query string:

In [30]:
df.query("IMDb > 8 and Year == 2018")

                Actor       Film  Year     Genre  BoxOffice(INR Crore)  IMDb
5  Ayushmann Khurrana  Andhadhun  2018  Thriller                   111   8.3

### 2. String values must be in quotes

Use **single or double** quotes around strings in the expression:

In [31]:
df.query("Actor == 'Aamir Khan'")

        Actor    Film  Year      Genre  BoxOffice(INR Crore)  IMDb
2  Aamir Khan  Dangal  2016  Biography                  2024   8.4

If you have quotes inside quotes, mix them:

Example: 

df.query('city == "Mumbai"')

### 3. Use backticks for column names with spaces or special characters

If a column name has spaces, use backticks ( ` ):

In [32]:
df.query("`BoxOffice(INR Crore)` == 342")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

### 4. You can use @ to reference Python variables

To pass external variables into .query():

In [33]:
earning = 500
df.query("`BoxOffice(INR Crore)` > @earning")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0

### 5. Logical operators
Use these:

* `and`, `or`, `not` — instead of `&`, `|`, `~`
* `==`, `!=`, `<`, `>`, `<=`, `>=`

*Bad:*

`df.query("age > 30 & city == 'Delhi'")  # ❌`

*Good:* 

`df.query("age > 30 and city == 'Delhi'")  # ✅`

### 6. Chained comparisons

Just like Python:

In [34]:
df.query("6 < IMDb <= 8")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1

### 7. Avoid using reserved keywords as column names

If you have a column named `class`, `lambda`, etc., you’ll need to use backticks:

Example:

df.query("`class` == 'Physics'")

## 8. Case-sensitive

Column names and string values are case-sensitive:

Example:

df.query("City == 'delhi'")  # ❌ if actual value is 'Delhi'

### 9. `.query()` returns a copy, not a view

The result is a new DataFrame. Changes won't affect the original unless reassigned:

In [35]:
filtered = df.query("IMDb < 7")

In [36]:
filtered

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Hrithik Roshan,War,2019,Action,475,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1

## Summary
* Use `df[col]`, `.loc[]`, `.iloc[]`, `.at[]`, `.iat[]` to access data
* Filter with logical conditions or `.query()` for readable code
* Mastering selection makes the rest of pandas feel easy