# Data Transformation

Once your data is clean, the next step is to **reshape, reformat, and reorder** it as needed for analysis. Pandas gives you plenty of flexible tools to do this.

---------------

In [53]:
import pandas as pd

In [54]:
df = pd.read_csv("data.csv")

In [55]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

--------------

## Sorting & Ranking

### Sort by Values

In [56]:
df.sort_values("Year")                   # Ascending sort

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [57]:
df.sort_values("Year", ascending=False)  # Descending

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [58]:
df.sort_values(["Year","IMDb"])

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

`df.sort_values(["Year","IMDb"])` sorts the DataFrame first by the "Year" column, and if there are ties (i.e., two or more rows with the same "Year"), it will sort by the "IMDb" column.

------------

## Reset Index

If you want the index to start from 0 and be sequential, you can reset it using `reset_index()`

In [59]:
df2 = df.sort_values(["Year","IMDb"]).copy()

In [60]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [61]:
df2.reset_index(drop=True, inplace=True)  # Reset the index and drop the old index

In [62]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

-----
## Sort by Index

In [63]:
df3 = df.sort_values(["Year","IMDb"]).copy()

In [64]:
df3

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [65]:
df3.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

The `df.sort_index()` function is used to sort the DataFrame based on its index values. If the index is not in a sequential order (e.g., you have dropped rows or performed other operations that change the index), you can use sort_index() to restore it to a sorted order.

-------------

## Ranking

The `.rank()` function in pandas is used to assign ranks to numeric values in a column, like scores or points. By default, it gives the average rank to tied values, which can result in decimal numbers. For example, if two people share the top score, they both get a rank of 1.5. You can customize the ranking behavior using the method parameter. One useful option is **method='dense'**, which assigns the same rank to ties but doesn’t leave gaps in the ranking sequence. This is helpful when you want a clean, consecutive ranking system without skips.

In [66]:
df["Rank"] = df["IMDb"].rank()                 # Default: average method

In [67]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0

In [68]:
df["Rank"] = df["IMDb"].rank(method="dense")   # 1, 2, 2, 3

In [69]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0

-----------

## Renaming Columns & Index

In [70]:
df.rename(columns={"IMDb": "Rating"}, inplace=True) #df.rename(columns={"oldName": "newName"}, inplace=True)

In [71]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),Rating,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0

In [72]:
df.rename(index={0: "Favourite", 11: "Not Seen"}, inplace=True) #df.rename(index={0: "row1", 1: "row2"}, inplace=True)

In [73]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),Rating,Rank
Favourite,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
Not Seen,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0

---------------
## Changing Column Order

Just pass a new list of column names:

In [74]:
df[["Year", "Actor", "Film"]]   # Reorder as desired

           Year               Actor                      Film
Favourite  2023      Shah Rukh Khan                   Pathaan
1          2017         Salman Khan           Tiger Zinda Hai
2          2016          Aamir Khan                    Dangal
3          2022       Ranbir Kapoor                Brahmastra
4          2018       Ranveer Singh                 Padmaavat
5          2018  Ayushmann Khurrana                 Andhadhun
6          2018       Rajkummar Rao                     Stree
7          2019      Hrithik Roshan                       War
8          2019        Akshay Kumar                Good Newwz
9          2022       Kartik Aaryan         Bhool Bhulaiyaa 2
10         2017        Varun Dhawan     Badrinath Ki Dulhania
Not Seen   2019       Vicky Kaushal  Uri: The Surgical Strike

In [75]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),Rating,Rank
Favourite,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
Not Seen,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0

You can also move one column to the front:

In [76]:
cols = ["Genre"] + [col for col in df.columns if col != "Genre"]

In [77]:
df = df[cols]

In [78]:
df

,Genre,Actor,Film,Year,BoxOffice(INR Crore),Rating,Rank
Favourite,Action,Shah Rukh Khan,Pathaan,2023,1050,7.2,7.0
1,Action,Salman Khan,Tiger Zinda Hai,2017,565,6.0,3.0
2,Biography,Aamir Khan,Dangal,2016,2024,8.4,11.0
3,Fantasy,Ranbir Kapoor,Brahmastra,2022,431,5.6,1.0
4,Historical,Ranveer Singh,Padmaavat,2018,585,7.0,6.0
5,Thriller,Ayushmann Khurrana,Andhadhun,2018,111,8.3,10.0
6,Horror Comedy,Rajkummar Rao,Stree,2018,180,7.5,8.0
7,Action,Hrithik Roshan,War,2019,475,6.5,5.0
8,Comedy,Akshay Kumar,Good Newwz,2019,318,7.0,6.0
9,Horror Comedy,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,266,5.9,2.0
10,Romantic Comedy,Varun Dhawan,Badrinath Ki Dulhania,2017,201,6.1,4.0
Not Seen,Action,Vicky Kaushal,Uri: The Surgical Strike,2019,342,8.2,9.0

## Summary
* Sort, rank, and rename to prepare your data
* Reordering and reshaping are key for EDA and visualization